locations = [
    {
        "country": "United States",
        "country_code": "US",
        "capital": "Washington, D.C.",
        "popular_cities": [
            "Washington, D.C.",
            "New York",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Phoenix",
            "Philadelphia",
            "San Antonio",
            "San Diego",
            "Dallas",
            "San Jose",
            "Austin",
            "Jacksonville",
            "Fort Worth",
            "Columbus",
            "San Francisco",
            "Charlotte",
            "Indianapolis",
            "Seattle",
            "Denver",
            "Washington, D.C.",
            "Boston",
            "El Paso",
            "Nashville",
            "Detroit",
            "Oklahoma City",
            "Portland",
            "Las Vegas",
            "Memphis",
            "Louisville",
            "Baltimore",
            "Milwaukee",
            "Albuquerque",
            "Tucson",
            "Fresno",
            "Mesa",
            "Sacramento",
            "Atlanta",
            "Kansas City",
            "Colorado Springs",
            "Miami",
            "Raleigh",
            "Omaha",
            "Long Beach",
            "Virginia Beach",
            "Oakland",
            "Minneapolis",
            "Tulsa",
            "Tampa",
            "Arlington",
            "New Orleans",
            "Wichita",
            "Cleveland",
            "Bakersfield",
            "Aurora",
            "Anaheim",
            "Honolulu",
            "Santa Ana",
            "Riverside",
            "Corpus Christi",
            "Lexington",
            "Henderson",
            "Stockton",
            "St. Paul",
            "Cincinnati",
            "St. Louis",
            "Pittsburgh",
            "Greensboro",
            "Lincoln",
            "Anchorage",
            "Plano",
            "Orlando",
            "Irvine",
            "Newark",
            "Toledo",
            "Durham",
            "Chula Vista",
            "Fort Wayne",
            "Jersey City",
            "St. Petersburg",
            "Laredo",
            "Madison",
            "Chandler",
            "Buffalo",
            "Lubbock",
            "Scottsdale",
            "Reno",
            "Glendale",
            "Gilbert",
            "Winston-Salem",
            "North Las Vegas",
            "Norfolk",
            "Chesapeake",
            "Garland",
            "Irving",
            "Hialeah",
            "Fremont",
            "Boise",
            "Richmond"
        ],
        "nationality": "American",
        "languages": ["English"]
    },
    {
        "country": "Canada",
        "country_code": "CA",
        "capital": "Ottawa",
        "popular_cities": [
            "Ottawa",
            "Toronto",
            "Vancouver",
            "Montreal",
            "Calgary",
            "Edmonton",
            "Ottawa",
            "Winnipeg",
            "Quebec City",
            "Hamilton",
            "Kitchener",
            "London",
            "Victoria",
            "Halifax",
            "Oshawa",
            "Windsor",
            "Saskatoon",
            "St. Catharines",
            "Regina",
            "St. John's",
            "Kelowna",
            "Barrie",
            "Sherbrooke",
            "Guelph",
            "Abbotsford",
            "Kingston",
            "Kanata",
            "Trois-Rivières",
            "Moncton",
            "Chicoutimi",
            "Milton",
            "Red Deer",
            "Brantford",
            "Thunder Bay",
            "Whitehorse",
            "Yellowknife",
            "Charlottetown"
        ],
        "nationality": "Canadian",
        "languages": ["English", "French"]
    },
    {
        "country": "France",
        "country_code": "FR",
        "capital": "Paris",
        "popular_cities": [
            "Paris",
            "Marseille",
            "Lyon",
            "Toulouse",
            "Nice",
            "Nantes",
            "Strasbourg",
            "Montpellier",
            "Bordeaux",
            "Lille",
            "Rennes",
            "Reims",
            "Le Havre",
            "Saint-Étienne",
            "Toulon",
            "Angers",
            "Grenoble",
            "Dijon",
            "Nîmes",
            "Aix-en-Provence",
            "Saint-Quentin-en-Yvelines",
            "Clermont-Ferrand",
            "Brest",
            "Limoges",
            "Tours",
            "Amiens",
            "Perpignan",
            "Metz",
            "Besançon",
            "Orléans",
            "Rouen",
            "Mulhouse",
            "Caen",
            "Boulogne-Billancourt",
            "Nancy",
            "Argenteuil",
            "Saint-Denis",
            "Montreuil",
            "Roubaix",
            "Avignon"
        ],
        "nationality": "French",
        "languages": ["French"]
    },
    {
        "country": "Japan",
        "country_code": "JP",
        "capital": "Tokyo",
        "popular_cities": [
            "Tokyo",
            "Osaka",
            "Kyoto",
            "Yokohama",
            "Nagoya",
            "Sapporo",
            "Kobe",
            "Fukuoka",
            "Hiroshima",
            "Sendai",
            "Kitakyushu",
            "Chiba",
            "Saitama",
            "Shizuoka",
            "Kawasaki",
            "Sagamihara",
            "Niigata",
            "Hamamatsu",
            "Okayama",
            "Kumamoto",
            "Kagoshima",
            "Funabashi",
            "Hachioji",
            "Matsuyama",
            "Matsudo",
            "Nagasaki",
            "Kanazawa",
            "Gifu",
            "Fukushima",
            "Shimonoseki",
            "Nara",
            "Toyama",
            "Akita",
            "Takamatsu",
            "Oita",
            "Yamagata",
            "Wakayama",
            "Utsunomiya",
            "Fukui",
            "Miyazaki"
        ],
        "nationality": "Japanese",
        "languages": ["Japanese"]
    },
    {
        "country": "Australia",
        "country_code": "AU",
        "capital": "Canberra",
        "popular_cities": [
            "Canberra",
            "Sydney",
            "Melbourne",
            "Brisbane",
            "Perth",
            "Adelaide",
            "Gold Coast",
            "Hobart",
            "Darwin",
            "Newcastle",
            "Wollongong",
            "Geelong",
            "Cairns",
            "Toowoomba",
            "Townsville",
            "Ballarat",
            "Bendigo",
            "Albury",
            "Launceston",
            "Mackay",
            "Rockhampton",
            "Bunbury",
            "Bundaberg",
            "Hervey Bay",
            "Wagga Wagga",
            "Coffs Harbour",
            "Gladstone",
            "Mildura",
            "Shepparton",
            "Port Macquarie",
            "Tamworth",
            "Traralgon",
            "Orange",
            "Geraldton",
            "Dubbo",
            "Bathurst",
            "Nowra",
            "Kalgoorlie",
            "Warrnambool"
        ],
        "nationality": "Australian",
        "languages": ["English"]
    },
    {
        "country": "Germany",
        "country_code": "DE",
        "capital": "Berlin",
        "popular_cities": [
            "Berlin",
            "Hamburg",
            "Munich",
            "Cologne",
            "Frankfurt",
            "Stuttgart",
            "Düsseldorf",
            "Dortmund",
            "Essen",
            "Leipzig",
            "Bremen",
            "Dresden",
            "Hannover",
            "Nuremberg",
            "Duisburg",
            "Bochum",
            "Wuppertal",
            "Bielefeld",
            "Bonn",
            "Münster",
            "Karlsruhe",
            "Mannheim",
            "Augsburg",
            "Wiesbaden",
            "Gelsenkirchen",
            "Mönchengladbach",
            "Braunschweig",
            "Chemnitz",
            "Kiel",
            "Aachen",
            "Halle",
            "Magdeburg",
            "Freiburg",
            "Krefeld",
            "Lübeck",
            "Oberhausen",
            "Erfurt",
            "Mainz",
            "Rostock"
        ],
        "nationality": "German",
        "languages": ["German"]
    },
    {
        "country": "India",
        "country_code": "IN",
        "capital": "New Delhi",
        "popular_cities": [
            "New Delhi",
            "Mumbai",
            "Bangalore",
            "Chennai",
            "Kolkata",
            "Hyderabad",
            "Pune",
            "Ahmedabad",
            "Jaipur",
            "Surat",
            "Lucknow",
            "Kanpur",
            "Nagpur",
            "Visakhapatnam",
            "Bhopal",
            "Patna",
            "Vadodara",
            "Ghaziabad",
            "Ludhiana",
            "Agra",
            "Nashik",
            "Faridabad",
            "Meerut",
            "Rajkot",
            "Kalyan-Dombivli",
            "Vasai-Virar",
            "Varanasi",
            "Srinagar",
            "Aurangabad",
            "Dhanbad",
            "Amritsar",
            "Navi Mumbai",
            "Allahabad",
            "Ranchi",
            "Howrah",
            "Coimbatore",
            "Jabalpur",
            "Gwalior",
            "Vijayawada",
            "Jodhpur"
        ],
        "nationality": "Indian",
        "languages": ["Hindi", "English"]
    },
    {
        "country": "Brazil",
        "country_code": "BR",
        "capital": "Brasília",
        "popular_cities": [
            "São Paulo",
            "Rio de Janeiro",
            "Salvador",
            "Fortaleza",
            "Belo Horizonte",
            "Brasília",
            "Curitiba",
            "Manaus",
            "Recife",
            "Belém",
            "Porto Alegre",
            "Goiânia",
            "Guarulhos",
            "Campinas",
            "São Luís",
            "São Gonçalo",
            "Maceió",
            "Duque de Caxias",
            "Natal",
            "Teresina",
            "Campo Grande",
            "São Bernardo do Campo",
            "Nova Iguaçu",
            "João Pessoa",
            "São José dos Campos",
            "Santo André",
            "Ribeirão Preto",
            "Jaboatão dos Guararapes",
            "Uberlândia",
            "Contagem",
            "Sorocaba",
            "Aracaju",
            "Feira de Santana",
            "Cuiabá",
            "Joinville",
            "Aparecida de Goiânia",
            "Londrina",
            "Juiz de Fora",
            "Ananindeua",
            "Niterói"
        ],
        "nationality": "Brazilian",
        "languages": ["Portuguese"]
    },
    {
        "country": "United Kingdom",
        "country_code": "GB",
        "capital": "London",
        "popular_cities": [
            "London",
            "Manchester",
            "Birmingham",
            "Leeds",
            "Glasgow",
            "Liverpool",
            "Bristol",
            "Sheffield",
            "Edinburgh",
            "Leicester",
            "Coventry",
            "Nottingham",
            "Kingston upon Hull",
            "Newcastle upon Tyne",
            "Cardiff",
            "Southampton",
            "Portsmouth",
            "Brighton",
            "Plymouth",
            "Derby",
            "Stoke-on-Trent",
            "Wolverhampton",
            "Swansea",
            "Oxford",
            "Cambridge",
            "Aberdeen",
            "Norwich",
            "York",
            "Peterborough",
            "Dundee",
            "Milton Keynes",
            "Reading",
            "Luton",
            "Swindon",
            "Warrington",
            "Huddersfield",
            "Basildon",
            "Bournemouth"
        ],
        "nationality": "British",
        "languages": ["English"]
    },
    {
        "country": "South Africa",
        "country_code": "ZA",
        "capital": "Pretoria",
        "popular_cities": [
            "Johannesburg",
            "Cape Town",
            "Durban",
            "Pretoria",
            "Port Elizabeth",
            "Bloemfontein",
            "East London",
            "Pietermaritzburg",
            "Benoni",
            "Tembisa",
            "Vereeniging",
            "Boksburg",
            "Welkom",
            "Kimberley",
            "Polokwane",
            "Rustenburg",
            "George",
            "Knysna",
            "Mbombela",
            "Grahamstown",
            "Soweto",
            "Mangaung",
            "Randburg",
            "Roodepoort",
            "Uitenhage",
            "Midrand",
            "Klerksdorp",
            "Bethlehem",
            "Springs",
            "Mthatha"
        ],
        "nationality": "South African",
        "languages": ["English", "Afrikaans", "Zulu", "Xhosa"]
    },
    {
        "country": "China",
        "country_code": "CN",
        "capital": "Beijing",
        "popular_cities": [
            "Shanghai",
            "Guangzhou",
            "Shenzhen",
            "Chengdu",
            "Hangzhou",
            "Beijing",
            "Wuhan",
            "Chongqing",
            "Tianjin",
            "Nanjing",
            "Xi'an",
            "Shenyang",
            "Harbin",
            "Qingdao",
            "Dalian",
            "Zhengzhou",
            "Changsha",
            "Kunming",
            "Jinan",
            "Fuzhou",
            "Shijiazhuang",
            "Ningbo",
            "Xiamen",
            "Wuxi",
            "Suzhou",
            "Changchun",
            "Taiyuan",
            "Urumqi",
            "Hefei",
            "Nanning",
            "Hohhot",
            "Lanzhou",
            "Guiyang",
            "Nanchang",
            "Yantai",
            "Zhuhai",
            "Haikou",
            "Luoyang",
            "Guilin"
        ],
        "nationality": "Chinese",
        "languages": ["Mandarin"]
    },
    {
        "country": "Mexico",
        "country_code": "MX",
        "capital": "Mexico City",
        "popular_cities": [
            "Guadalajara",
            "Monterrey",
            "Mexico City",
            "Puebla",
            "Tijuana",
            "León",
            "Ciudad Juárez",
            "Zapopan",
            "Monterrey",
            "Nezahualcóyotl",
            "Mexicali",
            "Mérida",
            "Toluca",
            "Chihuahua",
            "Naucalpan",
            "Cancún",
            "San Luis Potosí",
            "Aguascalientes",
            "Hermosillo",
            "Saltillo",
            "Morelia",
            "Culiacán",
            "Querétaro",
            "Mexicali",
            "Torreón",
            "Reynosa",
            "Durango",
            "Chimalhuacán",
            "Tlalnepantla",
            "Iztapalapa",
            "Ecatepec",
            "Acapulco",
            "Cuernavaca",
            "Villahermosa",
            "Tuxtla Gutiérrez",
            "Mazatlán",
            "Veracruz",
            "Tepic",
            "Matamoros",
            "Celaya"
        ],
        "nationality": "Mexican",
        "languages": ["Spanish"]
    },
    {
        "country": "Russia",
        "country_code": "RU",
        "capital": "Moscow",
        "popular_cities": [
            "Moscow",
            "Saint Petersburg",
            "Novosibirsk",
            "Yekaterinburg",
            "Nizhny Novgorod",
            "Kazan",
            "Chelyabinsk",
            "Omsk",
            "Samara",
            "Rostov-on-Don",
            "Ufa",
            "Krasnoyarsk",
            "Voronezh",
            "Perm",
            "Volgograd",
            "Krasnodar",
            "Saratov",
            "Tyumen",
            "Tolyatti",
            "Izhevsk",
            "Barnaul",
            "Ulyanovsk",
            "Irkutsk",
            "Khabarovsk",
            "Yaroslavl",
            "Vladivostok",
            "Makhachkala",
            "Tomsk",
            "Orenburg",
            "Kemerovo",
            "Novokuznetsk",
            "Ryazan",
            "Astrakhan",
            "Naberezhnye Chelny",
            "Penza",
            "Lipetsk",
            "Kirov",
            "Cheboksary",
            "Tula",
            "Kaliningrad"
        ],
        "nationality": "Russian",
        "languages": ["Russian"]
    },
    {
        "country": "Italy",
        "country_code": "IT",
        "capital": "Rome",
        "popular_cities": [
            "Rome",
            "Milan",
            "Naples",
            "Turin",
            "Palermo",
            "Genoa",
            "Bologna",
            "Florence",
            "Bari",
            "Catania",
            "Venice",
            "Verona",
            "Messina",
            "Padua",
            "Trieste",
            "Taranto",
            "Brescia",
            "Parma",
            "Prato",
            "Modena",
            "Reggio Calabria",
            "Reggio Emilia",
            "Perugia",
            "Ravenna",
            "Livorno",
            "Cagliari",
            "Foggia",
            "Rimini",
            "Salerno",
            "Ferrara",
            "Latina",
            "Giugliano in Campania",
            "Monza",
            "Siracusa",
            "Pescara",
            "Bergamo",
            "Forlì",
            "Trento",
            "Vicenza",
            "Terni"
        ],
        "nationality": "Italian",
        "languages": ["Italian"]
    },
    {
        "country": "Spain",
        "country_code": "ES",
        "capital": "Madrid",
        "popular_cities": [
            "Madrid",
            "Barcelona",
            "Valencia",
            "Seville",
            "Zaragoza",
            "Malaga",
            "Murcia",
            "Palma",
            "Las Palmas",
            "Bilbao",
            "Alicante",
            "Cordoba",
            "Valladolid",
            "Vigo",
            "Gijon",
            "L'Hospitalet de Llobregat",
            "Vitoria-Gasteiz",
            "Granada",
            "Elche",
            "Tarragona",
            "Badalona",
            "Cartagena",
            "Terrassa",
            "Jerez de la Frontera",
            "Sabadell",
            "Móstoles",
            "Santa Cruz de Tenerife",
            "Pamplona",
            "Almería",
            "San Sebastián",
            "Burgos",
            "Santander",
            "Castellón de la Plana",
            "Logroño",
            "Badajoz",
            "Salamanca",
            "Huelva",
            "Lleida",
            "Marbella",
            "Cadiz"
        ],
        "nationality": "Spanish",
        "languages": ["Spanish"]
    },
    {
        "country": "Azerbaijan",
        "country_code": "AZ",
        "capital": "Baku",
        "popular_cities": [
            "Baku",
            "Ganja",
            "Sumqayit",
            "Mingachevir",
            "Lankaran",
            "Shirvan",
            "Nakhchivan",
            "Shaki",
            "Yevlakh",
            "Khachmaz",
            "Goychay",
            "Barda",
            "Salyan",
            "Qazax",
            "Tartar",
            "Jalilabad",
            "Agjabadi",
            "Bilasuvar",
            "Gobustan",
            "Zaqatala",
            "Saatli",
            "Sabirabad",
            "Hajigabul",
            "Quba",
            "Baku",
            "Fuzuli",
            "Aghdam",
            "Zagatala",
            "Qabala",
            "Dashkesan",
            "Masalli",
            "Gadabay",
            "Zardab",
            "Imishli",
            "Astara",
            "Balakan",
            "Gusar",
            "Samukh",
            "Tovuz",
            "Ujar",
            "Lerik",
            "Kurdamir",
            "Susha",
            "Xankendi",
            "Baku",
            "Kalbacar",
            "Khojali"
        ],
        "nationality": "Azerbaijani",
        "languages": ["Azerbaijani", "Russian"]
    },
    {
        "country": "Turkey",
        "country_code": "TR",
        "capital": "Ankara",
        "popular_cities": [
            "Ankara",
            "Istanbul",
            "Izmir",
            "Bursa",
            "Antalya",
            "Adana",
            "Gaziantep",
            "Konya",
            "Kayseri",
            "Istanbul",
            "Mersin",
            "Eskişehir",
            "Diyarbakır",
            "Samsun",
            "Denizli",
            "Şanlıurfa",
            "Malatya",
            "Kahramanmaraş",
            "Erzurum",
            "Van",
            "Batman",
            "Balıkesir",
            "Istanbul",
            "Sakarya",
            "Trabzon",
            "Manisa",
            "Elazığ",
            "Hatay",
            "Aydın",
            "Afyonkarahisar",
            "Tekirdağ",
            "Isparta",
            "Çanakkale",
            "Mardin",
            "Istanbul",
            "Kütahya",
            "Osmaniye",
            "Edirne",
            "Aksaray",
            "Çorum",
            "Sivas",
            "Tokat",
            "Rize"
        ],
        "nationality": "Turkish",
        "languages": ["Turkish"]
    },
    {
        "country": "Iran",
        "country_code": "IR",
        "capital": "Tehran",
        "popular_cities": [
            "Mashhad",
            "Isfahan",
            "Karaj",
            "Shiraz",
            "Tabriz",
            "Qom",
            "Ahvaz",
            "Kermanshah",
            "Urmia",
            "Rasht",
            "Zahedan",
            "Tehran",
            "Hamadan",
            "Kerman",
            "Yazd",
            "Arak",
            "Ardabil",
            "Bandar Abbas",
            "Sanandaj",
            "Qazvin",
            "Khorramabad",
            "Zanjan",
            "Sari",
            "Gorgan",
            "Ilam",
            "Birjand",
            "Bojnurd",
            "Sabzevar",
            "Abadan",
            "Dezful",
            "Mahabad",
            "Neyshabur",
            "Babol",
            "Amol",
            "Qaem Shahr",
            "Semnan",
            "Kashan",
            "Saveh",
            "Malayer",
            "Bushehr"
        ],
        "nationality": "Iranian",
        "languages": ["Persian"]
    }
]


def find_country_by_country_code(country_code):
    for item in locations:
        if item['country_code'] == country_code:
            return item
    return None
